OficinaDePortugues.Web/OficinaDePortugues.Web/Models/ContactsModel.cs
namespace OficinaDePortugues.Web.Models
{
    public class ContactsModel
    {
    }
}

OficinaDePortugues.Web/OficinaDePortugues.Web/Models/CourseModel.cs
namespace OficinaDePortugues.Web.Models
{
    using OficinaDePortugues.Web.DTOs;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public class CourseModel
    {
        public CourseModel(string name)
        {
            this.Name = name;
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public MvcHtmlString Description { get; set; }

        public IEnumerable<string> Categories { get; set; }

        public string Price { get; set; }

        public string Duration { get; set; }

        public string RatingWidth { get; set; }

        public string ImageUrl { get; set; }

        public string Permalink { get; private set; }

        public static CourseModel From(CourseDto courseDto)
        {
            return new CourseModel(courseDto.Name)
            {
                Id = courseDto.Id,
                Description = new MvcHtmlString(courseDto.Description),
                Categories = courseDto.Categories,
                Permalink = courseDto.Permalink,
                Duration = courseDto.Duration,
                ImageUrl = courseDto.ImageUrl,
                Price = courseDto.Price.ToString("C"),
                RatingWidth = ((int)((courseDto.Rating * 100) / 5)).ToString()
            };
        }
    }
}

OficinaDePortugues.Web/OficinaDePortugues.Web/Models/CoursesModel.cs
namespace OficinaDePortugues.Web.Models
{
    using System.Collections.Generic;

    public class CoursesModel
    {
        public IEnumerable<CourseModel> Courses { get; set; }
    }
}

OficinaDePortugues.Web/OficinaDePortugues.Web/Models/OnlineApplicationModel.cs
namespace OficinaDePortugues.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public class OnlineApplicationModel
    {
        public IEnumerable<SelectListItem> Courses { get; set; }

        [Required]
        public string SelectedCourse { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? StartDate { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? EndDate { get; set; }

        [Required]
        public string Name { get; set; }

        [Required, EmailAddress]
        public string Email { get; set; }
    }
}

OficinaDePortugues.Web/OficinaDePortugues.Web/Models/OnlineApplicationResultModel.cs
namespace OficinaDePortugues.Web.Models
{
    public static class OnlineApplicationResultStatus
    {
        public static string MailSent = "mail_sent";

        public static string ValidationFailed = "validation_failed";

        public static string MailFailed = "mail_failed";
    }
}

OficinaDePortugues.Web/OficinaDePortugues.Web/Models/PricingModel.cs
namespace OficinaDePortugues.Web.Models
{
    public class PricingModel
    {
    }
}

OficinaDePortugues.Web/OficinaDePortugues.Web/Controllers/ContactsController.cs
namespace OficinaDePortugues.Web.Controllers
{
    using OficinaDePortugues.Web.Models;
    using System.Web.Mvc;

    public class ContactsController : Controller
    {
        public ActionResult Index()
        {
            var model = new ContactsModel();
            this.ViewBag.Title = "Contacts";

            return View(model);
        }
    }
}

OficinaDePortugues.Web/OficinaDePortugues.Web/Controllers/CourseDetailController.cs
namespace OficinaDePortugues.Web.Controllers
{
    using OficinaDePortugues.Repositories;
    using OficinaDePortugues.Web.Models;
    using System.Linq;
    using System.Web.Mvc;

    [RoutePrefix("courses/portuguese-course")]
    public class CourseDetailController : Controller
    {
        [Route("")]
        public ActionResult Index(string permalink)
        {
            var repository = new InMemoryCoursesRepository();

            var course = repository.GetCourses().FirstOrDefault(c => c.Permalink == permalink);

            if (course != null)
            {
                ViewBag.Title = course.Name;
                return View("Course", CourseModel.From(course));
            }

            return this.RedirectToAction("Index", "Courses");
        }
    }
}

OficinaDePortugues.Web/OficinaDePortugues.Web/Controllers/CoursesController.cs
namespace OficinaDePortugues.Web.Controllers
{
    using OficinaDePortugues.Repositories;
    using OficinaDePortugues.Web.Models;
    using System.Linq;
    using System.Web.Mvc;

    [RoutePrefix("portuguese-courses")]
    public class CoursesController : Controller
    {
        // GET: Courses
        [Route("")]
        public ActionResult Index()
        {
            var model = new CoursesModel();

            var repository = new InMemoryCoursesRepository();

            model.Courses = repository.GetCourses().Select(CourseModel.From);

            this.ViewBag.Title = "Courses";

            return View(model);
        }

        public ActionResult Pricing()
        {
            ViewBag.Title = "Pricing";
            return this.View(new PricingModel());
        }

        public ActionResult Promotions()
        {
            ViewBag.Title = "Promotions";
            return this.View("Promotions");
        }
    }
}

OficinaDePortugues.Web/OficinaDePortugues.Web/Controllers/HomeController.cs
namespace OficinaDePortugues.Web.Controllers
{
    using System.Web.Mvc;

    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

OficinaDePortugues.Web/OficinaDePortugues.Web/Controllers/OnlineApplicationController.cs
namespace OficinaDePortugues.Web.Controllers
{
    using OficinaDePortugues.Repositories;
    using OficinaDePortugues.Web.Models;
    using System.Linq;
    using System.Web.Mvc;

    [RoutePrefix("online-application")]
    public class OnlineApplicationController : Controller
    {
        [Route("")]
        public ActionResult Index(OnlineApplicationModel model)
        {
            //var model = new OnlineApplicationModel();

            var coursesRepository = new InMemoryCoursesRepository();
            var permalink = this.Request.QueryString["permalink"];

            model.Courses = coursesRepository.GetCourses().Select(dto => new SelectListItem
            {
                Text = dto.Name,
                Value = dto.Id.ToString(),
                Selected = permalink != null ? dto.Permalink == permalink : false
            });

            this.ViewBag.Title = "Online Application";

            return View(model);
        }

        [HttpPost]
        public JsonResult Register(OnlineApplicationModel model)
        {
            if (!this.ModelState.IsValid)
            {
                //faz cenas
                return this.Json(new { status = OnlineApplicationResultStatus.ValidationFailed });
            }

            return this.Json(new { status = OnlineApplicationResultStatus.MailSent, message = "Your message was sent successfully. Thanks." });
        }
    }
}

OficinaDePortugues.Web/OficinaDePortugues.Web/Controllers/TestimonialsController.cs
namespace OficinaDePortugues.Web.Controllers
{
    using System.Web.Mvc;

    public class TestimonialsController : Controller
    {
        // GET: Testimonials
        public ActionResult Index()
        {
            ViewBag.Title = "Testimonials";
            return this.View("Index");
        }
    }
}

OficinaDePortugues.Web/OficinaDePortugues.Web/Views/Courses/Index.cshtml
@model OficinaDePortugues.Web.Models.CoursesModel
<style type="text/css">

    #cmsmasters_row_5b283157f0f35 {
        background-color: #fbfbfb;
    }

        #cmsmasters_row_5b283157f0f35 .cmsmasters_row_outer_parent {
            padding-top: 70px;
        }

        #cmsmasters_row_5b283157f0f35 .cmsmasters_row_outer_parent {
            padding-bottom: 70px;
        }

    #cmsmasters_fb_5b2831baea90d {
        padding-top: 80px;
        padding-bottom: 80px;
        background-image: url(../wp-content/uploads/2015/08/Depositphotos_85241414_original.jpg);
        background-position: top center;
        background-repeat: no-repeat;
        background-attachment: scroll;
        background-size: cover;
    }

        #cmsmasters_fb_5b2831baea90d .featured_block_inner {
            width: 36%;
            padding: 70px 60px 70px 50px;
            text-align: left;
            float: left;
            background-color: rgba(22,158,183,0.8);
        }

        #cmsmasters_fb_5b2831baea90d .featured_block_text {
            text-align: left;
        }

    #cmsmasters_row_5b2831baeac2e .cmsmasters_row_outer_parent {
        padding-top: 0px;
    }

    #cmsmasters_row_5b2831baeac2e .cmsmasters_row_outer_parent {
        padding-bottom: 50px;
    }

    #cmsmasters_row_5b2831baeac2e .cmsmasters_row_inner.cmsmasters_row_fullwidth {
        padding-left: 0%;
    }

    #cmsmasters_row_5b2831baeac2e .cmsmasters_row_inner.cmsmasters_row_fullwidth {
        padding-right: 0%;
    }

    #cmsmasters_divider_5b2831baeacc4 {
        border-bottom-width: 1px;
        border-bottom-style: solid;
        padding-top: 0px;
        margin-bottom: 0px;
    }

    #cmsmasters_row_5b2831baead14 .cmsmasters_row_outer_parent {
        padding-top: 20px;
    }

    #cmsmasters_row_5b2831baead14 .cmsmasters_row_outer_parent {
        padding-bottom: 50px;
    }

    #cmsmasters_heading_5b2831baeada5 {
        text-align: center;
        margin-top: 0px;
        margin-bottom: 50px;
    }

        #cmsmasters_heading_5b2831baeada5 .cmsmasters_heading {
            text-align: center;
        }

            #cmsmasters_heading_5b2831baeada5 .cmsmasters_heading, #cmsmasters_heading_5b2831baeada5 .cmsmasters_heading a {
                font-weight: 300;
                font-style: normal;
            }

        #cmsmasters_heading_5b2831baeada5 .cmsmasters_heading_divider {
        }

    #cmsmasters_heading_5b2831baeadef {
        text-align: center;
        margin-top: 0px;
        margin-bottom: 20px;
    }

        #cmsmasters_heading_5b2831baeadef .cmsmasters_heading {
            text-align: center;
        }

            #cmsmasters_heading_5b2831baeadef .cmsmasters_heading, #cmsmasters_heading_5b2831baeadef .cmsmasters_heading a {
                font-weight: 300;
                font-style: normal;
            }

        #cmsmasters_heading_5b2831baeadef .cmsmasters_heading_divider {
        }

    #cmsmasters_row_5b2831baeae48 .cmsmasters_row_outer_parent {
        padding-top: 0px;
    }

    #cmsmasters_row_5b2831baeae48 .cmsmasters_row_outer_parent {
        padding-bottom: 70px;
    }

    #cmsmasters_pricing_item_5b2831baeb0d2 .cmsmasters_button:before {
        margin-right: .5em;
        margin-left: 0;
        vertical-align: baseline;
    }

    #cmsmasters_pricing_item_5b2831baeb0d2 .cmsmasters_button {
        font-family: 'Roboto';
        font-weight: 600;
        font-style: normal;
        border-style: solid;
    }

        #cmsmasters_pricing_item_5b2831baeb0d2 .cmsmasters_button:hover {
        }

    #cmsmasters_pricing_item_5b2831baeb257 .cmsmasters_button:before {
        margin-right: .5em;
        margin-left: 0;
        vertical-align: baseline;
    }

    #cmsmasters_pricing_item_5b2831baeb257 .cmsmasters_button {
        font-family: 'Roboto';
        font-weight: 600;
        font-style: normal;
        border-style: solid;
    }

        #cmsmasters_pricing_item_5b2831baeb257 .cmsmasters_button:hover {
        }

    #cmsmasters_pricing_item_5b2831baeb3a4 .cmsmasters_button:before {
        margin-right: .5em;
        margin-left: 0;
        vertical-align: baseline;
    }

    #cmsmasters_pricing_item_5b2831baeb3a4 .cmsmasters_button {
        font-family: 'Roboto';
        font-weight: 600;
        font-style: normal;
        border-style: solid;
    }

        #cmsmasters_pricing_item_5b2831baeb3a4 .cmsmasters_button:hover {
        }

    #cmsmasters_pricing_item_5b2831baeb5fd .cmsmasters_button:before {
        margin-right: .5em;
        margin-left: 0;
        vertical-align: baseline;
    }

    #cmsmasters_pricing_item_5b2831baeb5fd .cmsmasters_button {
        font-family: 'Roboto';
        font-weight: 600;
        font-style: normal;
        border-style: solid;
    }

        #cmsmasters_pricing_item_5b2831baeb5fd .cmsmasters_button:hover {
        }

    #cmsmasters_row_5b2831baeb6a9 {
        background-color: #01a2a6;
    }

        #cmsmasters_row_5b2831baeb6a9 .cmsmasters_row_outer_parent {
            padding-top: 50px;
        }

        #cmsmasters_row_5b2831baeb6a9 .cmsmasters_row_outer_parent {
            padding-bottom: 50px;
        }

    #cmsmasters_heading_5b2831baeb7b3 {
        text-align: center;
        margin-top: 0px;
        margin-bottom: 40px;
    }

        #cmsmasters_heading_5b2831baeb7b3 .cmsmasters_heading {
            text-align: center;
        }

            #cmsmasters_heading_5b2831baeb7b3 .cmsmasters_heading, #cmsmasters_heading_5b2831baeb7b3 .cmsmasters_heading a {
                font-weight: 300;
                font-style: normal;
                color: #ffffff;
            }

        #cmsmasters_heading_5b2831baeb7b3 .cmsmasters_heading_divider {
        }

    #cmsmasters_heading_5b2831baeb7ff {
        text-align: center;
        margin-top: 0px;
        margin-bottom: 40px;
    }

        #cmsmasters_heading_5b2831baeb7ff .cmsmasters_heading {
            text-align: center;
        }

            #cmsmasters_heading_5b2831baeb7ff .cmsmasters_heading, #cmsmasters_heading_5b2831baeb7ff .cmsmasters_heading a {
                font-weight: 300;
                font-style: normal;
                color: #ffffff;
            }

        #cmsmasters_heading_5b2831baeb7ff .cmsmasters_heading_divider {
        }

    #cmsmasters_button_5b2831baeb84f {
        text-align: center;
    }

        #cmsmasters_button_5b2831baeb84f .cmsmasters_button:before {
            margin-right: .5em;
            margin-left: 0;
            vertical-align: baseline;
        }

        #cmsmasters_button_5b2831baeb84f .cmsmasters_button {
            font-size: 12px;
            line-height: 35px;
            font-weight: 700;
            font-style: normal;
            padding-right: 25px;
            padding-left: 25px;
            border-width: 2px;
            border-style: solid;
            background-color: #01a2a6;
            color: #ffffff;
            border-color: #ffffff;
        }

            #cmsmasters_button_5b2831baeb84f .cmsmasters_button:hover {
                background-color: #ffffff;
                color: #01a2a6;
            }

    #cmsmasters_row_5b2831baeb8b2 .cmsmasters_row_outer_parent {
        padding-top: 70px;
    }

    #cmsmasters_row_5b2831baeb8b2 .cmsmasters_row_outer_parent {
        padding-bottom: 70px;
    }

    #cmsmasters_divider_5b2831baeba71 {
        border-bottom-width: 0px;
        border-bottom-style: solid;
        padding-top: 0px;
        margin-bottom: 50px;
    }

    #cmsmasters_icon_list_items_5b2831baebab8 {
        padding-left: 40px;
    }

        #cmsmasters_icon_list_items_5b2831baebab8 .cmsmasters_icon_list_item:before {
            font-size: 20px;
            left: -40px;
        }

        #cmsmasters_icon_list_items_5b2831baebab8 .cmsmasters_icon_list_item {
            line-height: 40px;
            padding: 0;
        }

            #cmsmasters_icon_list_items_5b2831baebab8 .cmsmasters_icon_list_item:before {
                line-height: 40px;
                top: 0;
            }

    .cmsmasters_icon_list_items #cmsmasters_icon_list_item_5b2831baebb1a:before {
        color: #fe5969;
    }

    .cmsmasters_icon_list_items #cmsmasters_icon_list_item_5b2831baebb5e:before {
        color: #fe5969;
    }

    .cmsmasters_icon_list_items #cmsmasters_icon_list_item_5b2831baebba0:before {
        color: #fe5969;
    }

    #cmsmasters_heading_5b2831baebc5e {
        text-align: left;
        margin-top: 15px;
        margin-bottom: 40px;
    }

        #cmsmasters_heading_5b2831baebc5e .cmsmasters_heading {
            text-align: left;
        }

            #cmsmasters_heading_5b2831baebc5e .cmsmasters_heading, #cmsmasters_heading_5b2831baebc5e .cmsmasters_heading a {
                font-weight: 300;
                font-style: normal;
            }
</style>

<div class="middle_content entry" role="main"></div>
<div id="cmsmasters_row_5b283157f0f35" class="cmsmasters_row cmsmasters_color_scheme_default cmsmasters_row_top_default cmsmasters_row_bot_default cmsmasters_row_boxed">
    <div class="cmsmasters_row_outer_parent">
        <div class="cmsmasters_row_outer">
            <div class="cmsmasters_row_inner">
                <div class="cmsmasters_row_margin">
                    <div class="cmsmasters_column one_first">
                        <div id="cmsmasters_learnpress_shortcode_5b283157f1039" class="cmsmasters_learnpress_shortcode cmsmasters_4">
                            @foreach (var course in Model.Courses)
                            {
                                <article id="lpr_course_post-@course.Id" class="lpr_course_post">
                                    <figure class="cmsmasters_img_rollover_wrap preloader"><img width="300" height="300" src="@course.ImageUrl" class="full-width wp-post-image" alt="@course.Name" title="@course.Name" srcset="http://language-school.cmsmasters.net/wp-content/uploads/2015/12/Depositphotos_63889211_original-300x300.jpg 300w, http://language-school.cmsmasters.net/wp-content/uploads/2015/12/Depositphotos_63889211_original-150x150.jpg 150w, http://language-school.cmsmasters.net/wp-content/uploads/2015/12/Depositphotos_63889211_original-60x60.jpg 60w, http://language-school.cmsmasters.net/wp-content/uploads/2015/12/Depositphotos_63889211_original-580x580.jpg 580w" sizes="(max-width: 300px) 100vw, 300px" /><div class="cmsmasters_img_rollover"><a href='@Url.Action("Index","CourseDetail", new { permalink = course.Permalink })' title="@course.Name" class="cmsmasters_open_post_link"></a></div></figure>

                                    <div class="lpr_course_inner">
                                        <header class="entry-header lpr_course_header">
                                            <h6 class="entry-title lpr_course_title"><a href='@Url.Action("Index","CourseDetail", new { permalink = course.Permalink })'>@course.Name</a></h6>
                                        </header>
                                        <div class="review-stars-rated">
                                            <div class="review-stars empty"></div>

                                            <div class="review-stars filled" style="width:@course.RatingWidth;"></div>
                                        </div><span class="cmsmasters_course_price">@course.Price</span>
                                    </div>
                                    <footer class="cmsmasters_course_footer">
                                        <div class="cmsmasters_cource_duration">@course.Duration</div>
                                        <div class="entry-meta cmsmasters_cource_cat">
                                            @foreach (var cat in course.Categories)
                                            {
                                                <a>@cat</a>

                                                if (course.Categories.Last() != cat)
                                                {
                                                    @Html.Raw(",");
                                                }
                                            }
                                        </div>
                                    </footer>
                                </article>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="cl"></div><div class="content_wrap fullwidth">
    <div class="middle_content entry" role="main"></div>
</div>
<div id="cmsmasters_row_5b2831baeb6a9" class="cmsmasters_row cmsmasters_color_scheme_default cmsmasters_row_top_default cmsmasters_row_bot_default cmsmasters_row_boxed">
    <div class="cmsmasters_row_outer_parent">
        <div class="cmsmasters_row_outer">
            <div class="cmsmasters_row_inner">
                <div class="cmsmasters_row_margin">
                    <div class="cmsmasters_column one_first">

                        <div id="cmsmasters_heading_5b2831baeb7b3" class="cmsmasters_heading_wrap cmsmasters_heading_align_center">
                            <h2 class="cmsmasters_heading">Check Out Special Promotion Here!</h2>
                        </div>
                        <div id="cmsmasters_heading_5b2831baeb7ff" class="cmsmasters_heading_wrap cmsmasters_heading_align_center">
                            <h4 class="cmsmasters_heading">Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Nihil hic munitissimus habendi senatus locus, nihil horum? Vivamus sagittis lacus vel augue laoreet rutrum faucibus.</h4>
                        </div>
                        <div id="cmsmasters_button_5b2831baeb84f" class="button_wrap"><a href="#" class="cmsmasters_button"><span>Check Out </span></a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

OficinaDePortugues.Web/OficinaDePortugues.Web/Views/Courses/Promotions.cshtml
<div class="middle_content entry" role="main"></div>
<style type="text/css">

    #cmsmasters_row_5b283252a7fb9 .cmsmasters_row_outer_parent {
        padding-top: 80px;
    }

    #cmsmasters_row_5b283252a7fb9 .cmsmasters_row_outer_parent {
        padding-bottom: 70px;
    }

    #cmsmasters_pricing_item_5b283252a8296 .cmsmasters_button:before {
        margin-right: .5em;
        margin-left: 0;
        vertical-align: baseline;
    }

    #cmsmasters_pricing_item_5b283252a8296 .cmsmasters_button {
        font-family: 'Roboto';
        font-weight: 600;
        font-style: normal;
        border-style: solid;
    }

        #cmsmasters_pricing_item_5b283252a8296 .cmsmasters_button:hover {
        }

    #cmsmasters_pricing_item_5b283252a8410 .cmsmasters_button:before {
        margin-right: .5em;
        margin-left: 0;
        vertical-align: baseline;
    }

    #cmsmasters_pricing_item_5b283252a8410 .cmsmasters_button {
        font-family: 'Roboto';
        font-weight: 600;
        font-style: normal;
        border-style: solid;
    }

        #cmsmasters_pricing_item_5b283252a8410 .cmsmasters_button:hover {
        }

    #cmsmasters_pricing_item_5b283252a856e .cmsmasters_button:before {
        margin-right: .5em;
        margin-left: 0;
        vertical-align: baseline;
    }

    #cmsmasters_pricing_item_5b283252a856e .cmsmasters_button {
        font-family: 'Roboto';
        font-weight: 600;
        font-style: normal;
        border-style: solid;
    }

        #cmsmasters_pricing_item_5b283252a856e .cmsmasters_button:hover {
        }

    #cmsmasters_pricing_item_5b283252a86cf .cmsmasters_button:before {
        margin-right: .5em;
        margin-left: 0;
        vertical-align: baseline;
    }

    #cmsmasters_pricing_item_5b283252a86cf .cmsmasters_button {
        font-family: 'Roboto';
        font-weight: 600;
        font-style: normal;
        border-style: solid;
    }

        #cmsmasters_pricing_item_5b283252a86cf .cmsmasters_button:hover {
        }
</style>

<div id="cmsmasters_row_5b283252a7fb9" class="cmsmasters_row cmsmasters_color_scheme_default cmsmasters_row_top_default cmsmasters_row_bot_default cmsmasters_row_boxed">
    <div class="cmsmasters_row_outer_parent">
        <div class="cmsmasters_row_outer">
            <div class="cmsmasters_row_inner">
                <div class="cmsmasters_row_margin">
                    <div class="cmsmasters_column one_first">

                        <div class="cmsmasters_pricing_table pricing_two">
                            <div id="cmsmasters_pricing_item_5b283252a8296" class="cmsmasters_pricing_item pricing_best">
                                <div class="cmsmasters_pricing_item_inner">
                                    <h3 class="pricing_title">A1: 50% Off</h3>
                                    <div class="cmsmasters_price_wrap">
                                        <span class="cmsmasters_price">260</span>
                                        <span class="cmsmasters_currency">€</span>
                                        <br /><span class="cmsmasters_period">per two weeks</span>
                                    </div>
                                    <ul class="feature_list">
                                        <li><span class="feature_icon cmsmasters-icon-check-1">from 9am to 1pm</span></li>
                                        <li><span class="feature_icon cmsmasters-icon-check-1">40 hours | 6,5€ per hour </span></li>
                                        <li><span class="feature_icon cmsmasters-icon-check-1">from 3rd to 14th September</span></li>
                                    </ul>
                                    <a href="@Url.Action("Index", "OnlineApplication", new
                                        {
                                            fromDate ="2018/09/03",
                                            toDate = "2018/09/14"
                                        })" class="cmsmasters_button"><span>Select</span></a>
                                </div>
                            </div>
                            <div id="cmsmasters_pricing_item_5b283252a8296" class="cmsmasters_pricing_item pricing_best">
                                <div class="cmsmasters_pricing_item_inner">
                                    <h3 class="pricing_title">A2: 50% Off</h3>
                                    <div class="cmsmasters_price_wrap">
                                        <span class="cmsmasters_price">260</span>
                                        <span class="cmsmasters_currency">€</span>
                                        <br /><span class="cmsmasters_period">per two weeks</span>
                                    </div>
                                    <ul class="feature_list">
                                        <li><span class="feature_icon cmsmasters-icon-check-1">from 9am to 1pm</span></li>
                                        <li><span class="feature_icon cmsmasters-icon-check-1">40 hours | 6,5€ per hour </span></li>
                                        <li><span class="feature_icon cmsmasters-icon-check-1">from 14th to 28th September</span></li>
                                    </ul>
                                    <a href="@Url.Action("Index", "OnlineApplication", new
                                        {
                                            fromDate =Html.Raw("2018/09/14"),
                                            toDate = "2018/09/28"
                                        })" class="cmsmasters_button"><span>Select</span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="cl"></div><div class="content_wrap fullwidth">
    <div class="middle_content entry" role="main"></div>
    <!-- _________________________ Finish Content _________________________ -->

OficinaDePortugues.Web/OficinaDePortugues.Web/Views/Shared/_FullWidthPagesLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Middle{
    <div id="middle">
        <div class="headline cmsmasters_color_scheme_first">
            <div class="headline_outer">
                <div class="headline_color"></div><div class="headline_inner align_left">
                    <div class="headline_aligner"></div><div class="headline_text"><h1 class="entry-title">@ViewBag.Title</h1></div><div class="cmsmasters_breadcrumbs">
                        <div class="cmsmasters_breadcrumbs_aligner"></div><div class="cmsmasters_breadcrumbs_inner">
                            <a href='@Url.Action("Index", "Home")' class="cms_home">Home</a>
                            <span class="breadcrumbs_sep"> / </span>
                            <span>@Html.Raw(ViewBag.Title)</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="middle_inner">
            <div class="content_wrap fullwidth">
            </div>

            @RenderBody()
        </div>
    </div>
}

@section scripts{

    @RenderSection("scripts", required: false)
}

OficinaDePortugues.Web/OficinaDePortugues.Web/Views/Shared/_PagesLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Middle{
    <div id="middle">
        <div class="headline cmsmasters_color_scheme_first">
            <div class="headline_outer">
                <div class="headline_color"></div>
            </div>
        </div>
        <div class="middle_inner">
            <div class="content_wrap fullwidth">
                @RenderBody()
            </div>
        </div>
    </div>
}

@section scripts{

    @RenderSection("scripts", required: false)
}